### PR TITLE
Add additional GL context information to capabilities struct

### PR DESCRIPTION
**Pull request by bitshifter**
Also added info example which outputs context information based on GLFW's glfwinfo test. Example output looks like:

```
OpenGL context verson: 4.3.0 - Build 10.18.15.4256
OpenGL context flags: debug
OpenGL profile mask: compatibility
OpenGL robustness strategy: none
OpenGL context renderer: Intel(R) HD Graphics 4600
OpenGL context vendor: Intel
```

### CODE REVIEW

**Comment by tomaka** [comment]
Perfect, thanks!

**Comment by tomaka** [comment]
Ah I didn't notice you didn't add getters.
The `CapabitiliesSource` trait is a hack around the problems with visibility in Rust. It's not supposed to be used in user code.

**Comment by bitshifter** [comment]
Ah right, I did notice getters on Context. I can add getters there. One question, I added the gl version string, I think it's useful since it has additional information over the Version struct. Maybe get_opengl_version_string() in addition to the existing get_opengl_version()? If yes then I'd probably also use get_opengl_renderer_string() and get_open_gl_vendor_string() for consistency.

**Comment by tomaka** [comment]
Sounds good.

**Pull request merged**
