### PR TITLE
Fix several compiler warnings

### PR DESCRIPTION
**Pull request by nicokoch**

### CODE REVIEW

**Comment by tomaka** [comment]
Thanks, however I'd prefer not to remove the `unwrap()`. They are real errors that could happen and that should be handled instead of being ignored.

**Comment by nicokoch** [comment]
You mean instead of `unwrap` we should match the result right?

**Comment by tomaka** [comment]
Just leave the warning for now. The error should be propagated.

**Comment by nicokoch** [comment]
I just updated this PR.

I also tried running [clippy](https://github.com/Manishearth/rust-clippy) on this crate, and ran into a compiler [bug](https://github.com/rust-lang/rust/issues/29174).

**Pull request merged**
