### PR TITLE
Improving error handling Issue #959

### PR DESCRIPTION
**Pull request by Roxxik**
Added Display and Error traits to all Errors

Ref: #959 

- Errors:
    - [x] src/buffer/alloc.rs: ReadError
    - [x] src/buffer/alloc.rs: CopyError
    - [x] src/buffer/mod.rs: BufferCreationError
    - [x] src/ops/read.rs: ReadError
    - [x] src/uniforms/mod.rs: LayoutMismatchError
    - [x] src/index/buffer.rs: CreationError
    - [x] src/texture/buffer_texture.rs: TextureCreationError
    - [x] src/texture/buffer_texture.rs: CreationError
    - [x] src/texture/mod.rs: TextureCreationError
    - [x] src/texture/get_format.rs: GetFormatError
    - [x] src/program/mod.rs: ProgramCreationError
    - [x] src/program/mod.rs: ProgramChooserCreationError
    - [x] src/program/mod.rs: GetBinaryError
    - [x] src/vertex/buffer.rs: CreationError
    - [x] src/vertex/transform_feedback.rs: TransformFeedbackSessionCreationError
    - [x] src/framebuffer/render_buffer.rs: CreationError
    - [x] src/draw_parameters/query.rs: QueryCreationError
    - [x] src/draw_parameters/query.rs: ToBufferError
    - [x] src/image_format.rs: FormatNotSupportedError
    - [x] src/lib.rs: DrawError
    - [x] src/lib.rs: SwapBuffersError
    - [x] src/fbo.rs: ValidationError

### CODE REVIEW

**Comment by tomaka** [comment]
Thanks!

I didn't merge immediately because I was a bit wary about the coding style, but in fact it doesn't really matter.

**Comment by Roxxik** [comment]
Haven't seen anything about coding style, if you want to have your code consistently styled, I'd recommend a styleguide or checking in a commit hook rust-fmt script

**Comment by tomaka** [comment]
I'd like to have a consistent style, but manually enforcing a styleguide is too annoying to do, and rustfmt is still unfinished.

**Comment by Roxxik** [comment]
ok I just try to keep the style to what i find, but i can't promise anything, would be easier if there was a style guide somewhere, even if it's not strictly enforced

**Pull request merged**
