### PR TITLE
Fix UniformTypeMismatch error in tutorial examples.

### LINKED ISSUE #1221: examples/tutorial-03b compiles but panics with UniformTypeMismatch error
I did a clone of the repo and tried to build the `tutorial-03b` example like this:

    $ cargo build --example tutorial-03b
    [lots of output]
    $ ./target/debug/examples/tutorial-03b
    thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: UniformTypeMismatch { name: "matrix", expected: FloatMat4 }', ../src/libcore/result.rs:734

### PR DESCRIPTION
**Pull request by caldwell**
Fixes #1221

### CODE REVIEW

**Comment by tomaka** [comment]
Oh thanks!

Could you also fix the code in `doc/tutorials/....md` (it's the same code)?

**Comment by caldwell** [comment]
Sure.

**Comment by caldwell** [comment]
I think I got them all. I wasn't quite sure if the one with the sin() and cos() needed it but I did it anyway because I figured it couldn't hurt.

**Comment by tomaka** [comment]
Thanks!

**Pull request merged**
