### PR TITLE
[Breaking change] Make everything single-threaded

### LINKED ISSUE #459: Threading model discussion
## How OpenGL works

To do something with OpenGL, there are three steps:

 - Create the context
 - Set the context as being the active context in the current thread
 - Call the `glSomething` functions

Where a function in a regular C library would look like `do_something(const Context* context, int param);`, OpenGL instead looks like `do_something(int param);` and operates on the context that is active in the current thread.

Additional restrictions: you can only have one active context per thread, and the same context can't be active in two different threads at the same time (though this sometimes works depending on the backend).

Also on windows it is **very** slow to change the current context. So we should avoid this too.

## How Glium currently handles this

Glium creates an internal background thread that is inaccessible from outside the library. The context is created by glium and set as current in this background thread. This ensures that the context isn't active anywhere else, and that the current context of the thread is never changed.

Then all function calls add a command to a queue that is executed by this background thread.

This approach has the following drawbacks:

- It is slower than raw OpenGL calls.
- Embedded platforms often can't afford an additional thread.
- Having hidden costs is not what you expect from a system language.

## What's the alternative?

Glium aims to be 100% safe, which is an additional constraint in the design.

There are two problems when you want to remove this background thread:

- We must ensure that we are on the right thread when calling OpenGL functions
- We must ensure that the current context didn't change

The first problem is easily solved by removing `Send` and `Sync` from *all* structs that represent an OpenGL object (the display, textures, buffers, etc.).

This has the disadvantage that glium users must do everything from within the same thread, possibly reimplementing something similar to the commands queue that currently exists in glium.

The second problem is a bit more annoying:

 - The user can call `MakeCurrent` manually, but the function is marked as unsafe so we can ignore this situation.
 - The user can create a second context in the same thread.
 - The user can use another OpenGL wrapper which also exposes a safe interface, and create a context in the same thread.

The only solution that I see to make this safe is calling `*GetCurrentContext()` before each OpenGL function call. I don't know how this affects performances.

## TL;DR

There are two alternatives: 

- Having a background thread (the current one)
- Not implementing Send+Sync and calling `GetCurrentContext()` all the time

### PR DESCRIPTION
**Pull request by tomaka**
Glium types no longer implement `Send` and `Sync`. No other change in the public API.
Should lead to a performances gain and something *closer to the metal*.

Need to add some safety and cleanup the code but I wanted to get some feedback first.

Close #459

### CODE REVIEW

**Comment by tomaka** [comment]
cc @palodequeso @TyOverby @XMPPwocky @rsaarelm @andrewrk @nilbold and all people that I know use glium

Is this a problem for you if all objects (`Display`, `Texture2d`, `VertexBuffer`, etc.) no longer implement `Send` and `Sync`?

**Comment by andrewrk** [comment]
I've given up on rust for now and went back to C++ :-(

So I no longer depend on glium.

**Comment by nilbold** [comment]
It shouldn't cause any significant problems with what I'm planning to do.

**Comment by TyOverby** [comment]
Nope, my code is all single-threaded anyway.

**Comment by dylanede** [comment]
So is this leading up to removing the dedicated context thread? I'm personally all for this. The choice of expenses due to multithreading should be left to the user, and they should be left to figure out how to synchronise all other data with the rendering thread. If so required such an abstraction as the one that already exists deep inside glium can be built on top of it instead at a later date.

**Comment by kmcallister** [comment]
Fine by me.

It would be great to have a companion library that provides a safe and high-level way to send textures and other resources between GL contexts.  This is unfortunately a huge, platform-specific pain.

**Comment by kmcallister** [comment]
cc @pcwalton

**Comment by ryanstew** [comment]
Per our discussion on IRC, this sounds like great news to me (particularly with direct exposure of a make_current() API to allow external libs to play inside the OpenGL context).

**Comment by XMPPwocky** [comment]
Wouldn't break anything for me.

**Comment by tomaka** [comment]
Thanks for the feedback!

For safety, there will be a flag in the context:
 - If the flag is set (it is by default), all calls to OpenGL functions will be preceded by `{glX/wgl}GetCurrentContext()` to check if the context is the current one, and `{glX/wgl}MakeCurrent` if necessary.
 - If the flag is clear, this verification won't be done. The only way to set this flag to 0 is through an unsafe API.

**Comment by tomaka** [comment]
I'm going to stop here for now in the PR.
The code is dirty, but implementing this correctly would be a huge amount of rework that would conflict with #553

**Comment by tomaka** [comment]
A new nightly came in-between and broke the build, but the last change is minor and I've successfully tested locally.

I'll merge in a few hours if no-one is opposed to this.

**Comment by tomaka** [comment]
:shipit:

**Pull request merged**
