### PR TITLE
Bump cgmath version to 0.5

### PR DESCRIPTION
**Pull request by bitshifter**
Update cgmath to latest.

I was using cgmath 0.5 in my project, which clashed with the cgmath 0.4 being used in glium.

### CODE REVIEW

**Comment by bjz** [comment]
Thanks!

We switched a number of functions over from pass-by-ref to pass-by-value. You'll need to fix [these usages here](https://travis-ci.org/tomaka/glium/jobs/94303777#L510-L559). Be sure to compile the tests with:

```sh
cargo test --features 'cgmath'
```

**Comment by bitshifter** [comment]
Ah, I thought that seemed far too easy :)

I didn't notice cgmath wasn't a default feature. I'll take a look.

**Comment by bjz** [comment]
\o/

**Comment by tomaka** [comment]
I think I'm going to remove support for cgmath and nalgebra, like I did for image.
The From/Into traits should be good enough I think.

**Comment by bjz** [comment]
:+1:

**Comment by bitshifter** [comment]
Seems reasonable, should I just close this PR then?

**Pull request closed without merging**
