### PR TITLE
Add basic utah teapot example

### PR DESCRIPTION
**Pull request by tomaka**
The example was added mostly for the model. There's no texture, no movement, etc.

### CODE REVIEW

**Comment by palodequeso** [comment]
Sweet! I didn't get a chance to work on that deferred example last night, but I'm going to work on it tonight.

**Comment by tomaka** [comment]
I've added some lighting to the teapot. However it doesn't have normals or adjacency infos, so I had to use only one normal per face.

**Comment by palodequeso** [comment]
Computing the normals isn't too hard. But I suppose that's out of the scope of Glium.

**Comment by tomaka** [comment]
Yeah I could probably just modify `teapot_model` to add a pass.

**Comment by palodequeso** [comment]
I mean, even if you generated them offline and changed the model. That way
you wouldn't need that geometry shader just to get some basic lighting.

**Comment by tomaka** [comment]
That's what I was thinking. However I don't want to bother rewriting the Rust code corresponding to a new model.

Instead I'm going to add some code in `teapot_model` that builds the normals and returns them as part of the vertex.

**Comment by palodequeso** [comment]
That makes sense.

**Pull request merged**
