### PR TITLE
Add Context accessors for new Capabilities members

### PR DESCRIPTION
**Pull request by bitshifter**

### CODE REVIEW

**Comment by bitshifter** [comment]
I forgot to run cargo test instead of cargo build, another commit incoming.

**Comment by bitshifter** [comment]
The circle ci build is failing because it can't connect to crates.io or something :disappointed:

**Comment by tomaka** [comment]
Thanks

**Comment by tomaka** [comment]
Oh, forgot to merge.

**Comment by bitshifter** [comment]
:+1:

**Pull request merged**
