### PR TITLE
Support texture upload to texture arrays.

### PR DESCRIPTION
**Pull request by mheistermann**
Support texture upload to 2d texture arrays.
Fix off-by-one when x==width.

### CODE REVIEW

**Comment by tomaka** [comment]
Hmm, I would find it surprising that `y` corresponds to array layers for 1D arrays.

**Comment by mheistermann** [comment]
Can't find anything about this in the glTexSubImage2D documentation, but at least https://www.opengl.org/sdk/docs/man/html/glCopyTexSubImage2D.xhtml states

> When target is GL_TEXTURE_1D_ARRAY then the y coordinate and height are treated as the start slice and number of slices to modify.

So i think it would make sense to just behave the same way.

**Comment by mheistermann** [comment]
If you prefer, I could add a seperate layer range parameter, just let me know.

**Comment by tomaka** [comment]
No I think that's fine.
You just need to rebase your branch over master and I'll merge.

**Comment by mheistermann** [comment]
Rebased

**Pull request merged**
