### PR TITLE
Retrieve glsl version from gl version

### PR DESCRIPTION
**Pull request by Futile**
This is meant to implement #513.

### CODE REVIEW

**Comment by palodequeso** [comment]
Just curious about which platforms you have tested this on?

**Comment by Futile** [comment]
Not sure what you mean. The implementation only matches on the GlVersion already retrieved by glium, and differentiates between gl and gl es. No open gl calls are performed.

**Comment by tomaka** [comment]
After some thoughts, I'd prefer if you removed `Version::get_glsl_version` and moved its body in `Display::get_supported_glsl_version`.

Since the `Version` struct can both mean an OpenGL version or a GLSL version, it wouldn't make sense to be able to call `get_glsl_version` on a `Version` object that already represents a GLSL version.

**Comment by Futile** [comment]
Yeah, I noticed that aswell. So moving into `Display::get_supported_glsl_version` is preferred over copying `version::Version` and its `PartialOrd` implementation into a new type `GlslVersion`?

Although only of secondary concern, but moving into `Display::get_supported_glsl_version` will also make testing more difficult and less atomic.

**Comment by tomaka** [comment]
You could also write:

```rust
pub struct Version(Api, u8, u8);

impl Version {
    ...
}

// this function is invisible to the outside since the "version" module is private
pub fn gl_version_to_glsl_version(_: &Version) -> Version {
    ...
}

#[cfg(test)]
mod test {
    ...
}
```

**Comment by tomaka** [comment]
You will need to rebase over master so that travis passes.

**Pull request merged**
